v3.5 compatability updates
workarea-commerce/workarea-braintree pull request #1
Opened 2019-11-11 18:22 UTC by jyucis

no change log

BRAINTREE-1

2019-11-11 20:03 UTC, tubbo requested changes

2019-11-11 20:03 UTC, tubbo commented on .github/workflows/ci.yml
> +    - uses: workarea-commerce/ci/eslint@v1
there's no JS in this plugin so you don't need this.

2019-11-12 14:03 UTC, bencrouse requested changes
Can you remove the unneeded linting?

2019-11-15 14:45 UTC, bencrouse approved these changes

2019-11-15 14:45 UTC, merged