Add PayPal BN Code to Braintree Gateways
workarea-commerce/workarea-braintree pull request #3
Opened 2020-02-25 17:06 UTC by tubbo

The BN code for PayPal revenue attribution has now been added to all
Braintree gateway requests using the global `.application_id` parameter.
This maps to the `:channel` in Braintree's API.

**More info:**
- https://developers.braintreepayments.com/reference/request/transaction/sale/ruby#channel
- https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/braintree_blue.rb#L608

2020-02-26 14:34 UTC, bencrouse approved these changes

2020-02-26 14:35 UTC, bencrouse requested changes
Can you add a "no changelog" for the simplecov fix? An implementer wouldn't care.

2020-02-26 15:39 UTC, mttdffy approved these changes

2020-02-27 14:33 UTC, bencrouse approved these changes

2020-02-27 14:34 UTC, merged